apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-registry
data:
  dockerconfigjson: bm90LXNldA==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: email-secret
data:
  EMAIL_HOST_USER: bm90LXNldA==
  EMAIL_HOST_PASSWORD: bm90LXNldA==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
data:
  DB_USER: bm90LXNldA==
  DB_PASSWORD: bm90LXNldA==
  DB_HOST: bm90LXNldA==
  DB_PORT: bm90LXNldA==
  DB_NAME: bm90LXNldA==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scores-secret
data:
  SECRET_KEY: bm90LXNldA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scores-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  SITE_URL: "https://scores.example.com"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.example.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "true"
  DEFAULT_FROM_EMAIL: "noreply@example.com"
  SCORE_EXPIRATION_DAYS: "7"
