{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: scores-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: scores-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ print .Values.image .Values.tag }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "python manage.py migrate --noinput && python manage.py setup_demo_games"]
          envFrom:
          - secretRef:
              name: postgres-secret
          - secretRef:
              name: scores-secret
          - configMapRef:
              name: scores-config
      imagePullSecrets:
      - name: github-registry
{{- end }}
