# Generated by Django 5.2.8 on 2025-12-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_customize',
            field=models.BooleanField(default=False),
        ),
    ]
