# Generated by Django 5.2.8 on 2025-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_scores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
