# Generated by Django 5.2.8 on 2025-11-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('api_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('sort_order', models.CharField(choices=[('desc', 'Highest First'), ('asc', 'Lowest First')], default='desc', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='games.game')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('score', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leaderboards.leaderboard')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['leaderboard', '-score'], name='leaderboard_leaderb_96cc25_idx'), models.Index(fields=['expires_at'], name='leaderboard_expires_bb3170_idx')],
            },
        ),
    ]
