# Generated by Django 5.2.8 on 2025-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['leaderboard', 'player_id'], name='leaderboard_leaderb_91e290_idx'),
        ),
    ]
