# Generated by Django 5.2.8 on 2025-12-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_add_player_id_to_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='leaderboard_type',
            field=models.CharField(choices=[('score', 'Score'), ('correct_answer', 'Correct Answer')], default='score', max_length=20),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='show_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='show_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='sort_order',
            field=models.CharField(choices=[('desc', 'Highest First'), ('asc', 'Lowest First'), ('newest', 'Newest First'), ('oldest', 'Oldest First')], default='desc', max_length=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
