# Generated by Django 5.2.8 on 2025-12-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_leaderboard_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='max_scores',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='min_scores_to_keep',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
