# Generated by Django 5.2.8 on 2025-12-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_add_retention_policy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
