# Generated by Django 6.0 on 2026-06-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_change_score_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='reset_period',
            field=models.CharField(choices=[('none', 'No reset (lifetime)'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', help_text='Reset the leaderboard each day/week. Past periods stay viewable.', max_length=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
